version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    image: watch_shop
    container_name: watch_shop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      watch_shop:
        ipv4_address: 192.168.1.2

  db:
    image: mysql:8.0
    container_name: watch_shop-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      watch_shop:
        ipv4_address: 192.168.1.3

  nginx:
    image: nginx:alpine
    container_name: watch_shop-nginx
    restart: unless-stopped
    ports:
      - 8006:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      watch_shop:
        ipv4_address: 192.168.1.4

networks:
  watch_shop:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  db_data:
